// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table tb_paymentmodes {
    hjmpTS int [pk]
    createdTS string [null]
    modifiedTS string
    TypePkString string
    OwnerPkString string
    PK string
    sealed string
    p_active string
    p_code string
    p_paymentinfotype string
    aCLTS string
    propTS string
    p_net string
    p_sapcode string
    p_b2bactive string
    p_showinstallmentspdp string
}

